config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :projects do 
    resources :tasks,only:[:create,:destroy]
  end
  root 'projects#index'
  get 'timetables/index'
  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	validates :title,presence: {message: "入力してください"}
	validates :Professor_name,presence: {message: "入力してください"}
	validates :Days,presence: {message: "入力してください"}
	validates :Times,presence: {message: "入力してください"}
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	validates :title, presence: true
	scope :unfinished, -> { where(done: false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project,only:[:show,:edit,:update,:destroy]

	def set_project
		@project = Project.find(params[:id])
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	def index
		@projects = Project.where(Email: current_user.email)
	end

	def show
	end

	def new
		@project = Project.new
	end

	def edit
	end
	
	def create
		@project = Project.new(project_params)
		@project.Email = current_user.email
		if @project.save
			redirect_to projects_path
		else
			render 'new'
		end
	end

	def update
		if @project.update(project_params)
			redirect_to projects_path
		else
			render 'edit'
		end
	end


	private



	def project_params

		#cation!!
		params[:project].permit(:title,:Professor_name,:Days,:Times,:Email,:Days2,:Times2)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create
		@project = Project.find(params[:project_id])
		@task = @project.tasks.create(task_params)
		redirect_to project_path(@project.id)
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to project_path(params[:project_id])
	end

	def toggle
		render nothing: true
		@task = Task.find(params[:id])
		@task.done = !@task.done
		@task.save
		@project = Project.find(params[:project_id])
	end


	private

	def task_params
		params[:task].permit(:title)
	end

end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
	def index
		@projects = Project.where(Email: current_user.email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HOMEWORK MANAGER</title>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= include_gon %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
      <div class="container">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/projects">HOMEWORK MANAGER</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="navbar-nav nav">
              <% if user_signed_in? %>
                <li class= "<%= 'active' if controller.controller_name == 'projects' %>"><%= link_to 'TIMELINE', projects_path %></li>
                <li class= "<%= 'active' if controller.controller_name == 'timetables' %>"><%= link_to 'TIMETABLE',"/timetables/index" %></li>
                <li class= "<%= 'active' if request.path_info == '/users/edit' %>"><%= link_to 'PROFILE', edit_user_registration_path %></li>
                <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'TIMELINE', projects_path %></li>
                <li><%= link_to 'TIMETABLE','' %></li>
                <li><%= link_to 'SIGN UP',new_user_registration_path %></li>
                <li><%= link_to 'LOGIN', new_user_session_path %></li>
              <% end %>
            </ul>
            <ul class="navbar-nav nav navbar-right">
              <% if user_signed_in? %>
                <li><a href="">Logged in as <%= current_user.email %>.</a></li>
              <% else %>
                <li><a href="">
                  <% flash.each do |name, msg| %>
                    <%= content_tag :div, msg, id: "flash_#{name}" %>
                  <% end %>
                <% end %>
              </a></li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <section>
      <br>
      <br>
      <%= yield %>
    </section>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% f.label :Professor_name, "Professor" %>
  <br>
  <div class="field">
    <div class ="form_text">Subject name</div>
    <%= f.text_field :title %>
    <% if @project.errors.any? %>
      <%= @project.errors.messages[:title][0] %>
    <% end %>
  </div>
  <br>
  <div class="field">
    <div class ="form_text">Professor</div>
    <%= f.text_field :Professor_name %>
    <% if @project.errors.any? %>
		  <%= @project.errors.messages[:Professor_name][0] %>
    <% end %>
  </div>
  <br>
  <div class="field">
    <div class ="form_text">Date(2units)</div>
    <%= f.select :Days, {'月曜日' => '月' , '火曜日' => '火', '水曜日' => '水', '木曜日' => '木', '金曜日' => '金', '土曜日' => '土', '日曜日' => '日'} %>
    <%= f.select :Times, {'1限目' => 1 , '2限目' => 2, '3限目' => 3, '4限目' => 4, '5限目' => 5, '6限目' => 6, '7限目' => 7} %>
  </div>
  <br>
  <div class="field">
    <div class ="form_text">Date(2units)</div>
    <%= f.select :Days2, {'なし' => 'なし' ,'月曜日' => '月' , '火曜日' => '火', '水曜日' => '水', '木曜日' => '木', '金曜日' => '金', '土曜日' => '土', '日曜日' => '日'} %>
    <%= f.select :Times2, {'なし' => 0 ,'1限目' => 1 , '2限目' => 2, '3限目' => 3, '4限目' => 4, '5限目' => 5, '6限目' => 6, '7限目' => 7} %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class ="page_title">
	<%= @project.title %>
</div>
<div class ="page_sub_title">
	<%= @project.Professor_name %>
	<% if @project.Times2 != "なし" && @project.Days2 != "なし" then %>
		(<%= @project.Days %>曜<%= @project.Times %>限目,<%= @project.Days2 %>曜<%= @project.Times2 %>限目)
	<% else %>
		(<%= @project.Days %>曜<%= @project.Times %>限目)
	<% end %>
</div>
<br>
<%= render 'form' %>

app/views/projects/index.html.erb
<% if user_signed_in? %>
	<div class ="page_title">TIMELIST</div>
	<br>
	<% days = ["月","火","水","木","金","土","日"] %>
	<table class="table table-condensed table-bordered">
  	<thead>
    	<tr class="active">
				<th>Option</th>
				<th>Subject</th>
				<th>Issues</th>
				<th>Processed</th>
				<th>Professor</th>
				<th>Lecture Date</th>
    	</tr>
  	</thead>
  	<tbody>
			<tr class="active">
				<td width="15%">
					<ul class="nav nav-pills">
						<li><%= link_to "add" ,new_project_path %><span class="badge"></span></li>
					</ul>
				</td>
				<td width="40%"></td>
				<td width="10%"></td>
				<td width="10%"></td>
				<td width="10%"></td>
				<td width="15%"></td>
			</tr>
			<% for days_index in 0..6 do %>
				<% for time_index in 1..7 do %>
						<% @projects.each do |project| %>
							<% if time_index.to_s == project.Times && days[days_index] == project.Days then %>
								<% if project.tasks.count !=0 then %>
									<tr class="info">
								<% else %>
									<tr class="active">
								<% end %>
								<td width="15%">
									<ul class="nav nav-pills">
  									<li><%= link_to "delete",project_path(project.id),method: :delete %><span class="badge"></span></a></li>
  									<li><%= link_to "edit",edit_project_path(project.id) %><span class="badge"></span></li>
	  	 						</ul>
	  	 					</td>
								<td width="40%">
									<ul class="nav nav-pills">
										<li><%= link_to project.title,project_path(project.id) %><span class="badge"></span></li>
									</ul>
								</td>
								<td width="10%">
									(<%= project.tasks.count - project.tasks.unfinished.count %>/<%= project.tasks.count %>)
								</td>
								<td width="10%">
									<% if project.tasks.count != 0 then %>
										<%= 100 * (project.tasks.count - project.tasks.unfinished.count) / project.tasks.count %>
									<% else %>
										<%= 0 %>
									<% end %>%
								</td>
								<td width="10%">
									<%= project.Professor_name %>
								</td>
								<td width="15%">
									<% if project.Times2 != "なし" && project.Days2 != "なし" then %>
										<%= project.Days %>曜<%= project.Times %>限目,<%= project.Days2 %>曜<%= project.Times2 %>限目
									<% else %>
										<%= project.Days %>曜<%= project.Times %>限目
									<% end %>
								</td>
							<% end %>
						<% end %>
					</tr>
				<% end %>
			<% end %>
  	</tbody>
	</table> 
<% end %>

app/views/projects/new.html.erb

<div class ="page_title">Add Subject</div>
<br>
<%= render 'form' %>

app/views/projects/show.html.erb

<div class ="page_title">
	<%= @project.title %>
</div>
<div class ="page_sub_title">
	<%= @project.Professor_name %>
	<% if @project.Times2 != "なし" && @project.Days2 != "なし" then %>
		(<%= @project.Days %>曜<%= @project.Times %>限目,<%= @project.Days2 %>曜<%= @project.Times2 %>限目)
	<% else %>
		(<%= @project.Days %>曜<%= @project.Times %>限目)
	<% end %>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-striped active progress-bar-waring" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
  </div>
</div>
<br>
<br>
<table class="table table-striped table-bordered" style="background: #FFF;">
<thead>
	<tr>
	<th>Check</th>
	<th>Option</th>
	<th>Homework</th>
	</tr>
</thead>
<tbody>
	<% @project.tasks.each do |task| %>
		<tr>
			<td width="10%">
				<%= check_box_tag '','',task.done,{'data-id' => task.id,'data-project_id' => task.project_id} %>
			</td>
			<td width="10%">
				<ul class="nav nav-pills">
					<li><%= link_to "delete",project_task_path(task.project_id,task.id),method: :delete %><span class="badge"></span></a></li>
				</ul>
			</td>
			<td width="80%">
				<ul class="nav nav-pills">
					<li><%= link_to task.title,"" %><span class="badge"></span></a></li>
				</ul>
			</td>
		</tr>
	<% end %>
</table> 
<br>
<br>
<div class="form">
	<%= form_for [@project,@project.tasks.build] do |f| %>
	<%= f.text_field :title %>
	<br>
	<br>
	<%= submit_tag "課題を追加" %>
	<% end %>
</div>
<%= javascript_tag do %>
  window.tasks_count = <%= raw @project.tasks.count %>;
  window.tasks_unfinished_count = <%= raw @project.tasks.unfinished.count %>;
<% end %>
<script>
$(function(){
	var n = 0;
	var str = "";
	if( window.tasks_count != 0){
		n = 100 * (window.tasks_count - window.tasks_unfinished_count) / window.tasks_count;
	}
	str += n;
	str += "%";
	$('.progress-bar').css('width', str);
	$("input[type=checkbox]").click(function(){
		$.post('/projects/'+ $(this).data('project_id') +'/tasks/'+ $(this).data('id') +'/toggle');
		location.reload();
		$('.progress-bar').css('width', "0%");
	});
});
</script>

app/views/timetables/index.html.erb

<% if user_signed_in? %>
	<div class ="page_title">TIMETABLE</div>
	<br>
	<% days = ["月","火","水","木","金","土","日"] %>
	<table class="table table-bordered table-condensed" >
  	<thead>
		<tr class="active">
		<th></th>
		<th>月</th>
		<th>火</th>
		<th>水</th>
		<th>木</th>
		<th>金</th>
		<th>土</th>
		<th>日</th>
		</tr>
  	</thead>
  	<tbody>
  		<% for time_index in 1..7 do %>
				<tr class="active">
				<td 　width="9%"><%= time_index %>限</td>
				<% for days_index in 0..6 do %>
					<td 　width="13%">
						<% @projects.each do |project| %>
							<% if time_index.to_s == project.Times && days[days_index] == project.Days then %>
								<ul class="nav nav-pills">
									<li><%= link_to project.title,project_path(project.id) %><span class="badge"></span></a></li>
								</ul>
							<% end %>
							<% if time_index.to_s == project.Times2 && days[days_index] == project.Days2 then %>
								<ul class="nav nav-pills">
									<li><%= link_to project.title,project_path(project.id) %><span class="badge"></span></a></li>
								</ul>
							<% end %>
						<% end %>
					</td>
				<% end %>
				</tr>
			<% end %>
			<tr class="active">
			<td 　width="9%">
				<%= link_to "add" ,new_project_path %>
			</td>
			<td 　width="13%"></td>
			<td 　width="13%"></td>
			<td 　width="13%"></td>
			<td 　width="13%"></td>
			<td 　width="13%"></td>
			<td 　width="13%"></td>
			<td 　width="13%"></td>
			</tr>
  	</tbody>
	</table> 
<% end %>